language: php
php:
    - 7.3
    - 7.4
    - 8.0

cache:
    directories:
        - node_modules

install:
    - echo "{\"http-basic\":{\"nova.laravel.com\":{\"username\":\"${NOVA_USERNAME}\",\"password\":\"${NOVA_PASSWORD}\"}}}" > auth.json
    - composer install
    - npm ci

script:
    - composer test
    - npm run lint
